id = "csharp"
name = "C#"
description = "C# support"
version = "0.2.0"
schema_version = 1
authors = ["nulifyer <zed-csharp-ext.caress448@passmail.net>"]
repository = "https://github.com/Nulifyer/zed-csharp"

[language_servers.csharp-language-server]
name = "csharp-ls"
language = "CSharp"

[debug_adapters.csharp]
schema_path = "debug_adapter_schemas/csharp.json"

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
commit = "dd5e59721a5f8dae34604060833902b882023aaf"

[grammars.xml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
commit = "4b64dd3a03ec002258d6268d712fd93716d6ab57"
