id = "csharp"
name = "C#"
description = "C# support"
version = "0.2.0"
schema_version = 1
authors = ["nulifyer <zed-csharp-ext.caress448@passmail.net>"]
repository = "https://github.com/Nulifyer/zed-csharp"

[language_servers.csharp-roslyn]
name = "csharp-roslyn"
language = "CSharp"

[language_servers.csharp-razor]
name = "csharp-razor"
language = "Razor"

[debug_adapters.coreclr]
schema_path = "debug_adapter_schemas/coreclr.json"

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
commit = "dd5e59721a5f8dae34604060833902b882023aaf"

[grammars.razor]
repository = "https://github.com/tris203/tree-sitter-razor"
commit = "fe46ce5ea7d844e53d59bc96f2175d33691c61c5"
