id = "csharp"
name = "C#"
description = "C# support."
version = "0.1.3"
schema_version = 1
authors = ["fminkowski <fminkowski@gmail.com>"]
repository = "https://github.com/zed-extensions/csharp"

[language_servers.omnisharp]
name = "OmniSharp"
language = "CSharp"

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
commit = "6563c3af3f03ec948d08f9325e4bbd072e4c6b99"
