id = "csharp"
name = "C#"
description = "C# support"
version = "0.2.0"
schema_version = 1
authors = ["nulifyer <zed-csharp-ext.caress448@passmail.net>"]
repository = "https://github.com/Nulifyer/zed-csharp"

[language_servers.csharp-language-server]
name = "csharp-language-server"
languages = ["CSharp"]

[language_servers.csharp-language-server.language_ids]
"CSharp" = "csharp"

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
commit = "dd5e59721a5f8dae34604060833902b882023aaf"

[grammars.razor]
repository = "https://github.com/tris203/tree-sitter-razor"
commit = "fe46ce5ea7d844e53d59bc96f2175d33691c61c5"

[grammars.html]
repository = "https://github.com/tree-sitter/tree-sitter-html"
commit = "bfa075d83c6b97cd48440b3829ab8d24a2319809"

[grammars.css]
repository = "https://github.com/tree-sitter/tree-sitter-css"
commit = "dda5cfc5722c429eaba1c910ca32c2c0c5bb1a3f"

[grammars.javascript]
repository = "https://github.com/tree-sitter/tree-sitter-javascript"
commit = "44c892e0be055ac465d5eeddae6d3e194424e7de"

[grammars.xml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
commit = "863dbc381f44f6c136a399e684383b977bb2beaa"
path = "xml"

[debug_adapters.coreclr]
schema_path = "debug_adapter_schemas/netcoredbg.json"

[debug_adapters.netcoredbg]
schema_path = "debug_adapter_schemas/netcoredbg.json"
