name = "C# Project File"
grammar = "xml"
path_suffixes = ["csproj"]
first_line_pattern = '^<.*Project\sSDK=".*">$'
block_comment = ["<!-- ", " -->"]
brackets = [{ start = "<", end = ">", close = true, newline = true }]
prettier_parser_name = "xml"
prettier_plugins = ["@prettier/plugin-xml"]