name = "C# Project File"
path_suffixes = ["csproj", "props", "targets", "resx", "xml"]
line_comments = []
block_comment = ["<!-- ", " -->"]
tab_size = 2
hard_tabs = false
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "<!--", end = "-->", close = true, newline = false },
    { start = "<", end = ">", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
]