name = "CSharp"
code_fence_block_name = "csharp"
grammar = "c_sharp"
path_suffixes = ["cs"]
line_comments = ["// ", "/// "]
block_comment = ["/* ", " */"]
tab_size = 4
hard_tabs = false
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "/*", end = " */", close = true, newline = false, not_in = ["string", "comment"] },
]
